# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# $Id: Makefile.am,v 1.10 2011/02/14 20:39:40 nicm Exp $


pkgdatadir = $(datadir)/tmux
pkgincludedir = $(includedir)/tmux
pkglibdir = $(libdir)/tmux
pkglibexecdir = $(libexecdir)/tmux
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-apple-darwin10.7.0
host_triplet = x86_64-apple-darwin10.7.0
bin_PROGRAMS = tmux$(EXEEXT)

# glibc as usual does things ass-backwards and hides useful things by default,
# so everyone has to add this.
#am__append_1 = -D_GNU_SOURCE

# Set flags for gcc. gcc4 whines abouts silly stuff so it needs slightly
# different flags.
am__append_2 = -std=c99
am__append_3 = -g -ggdb -O0 -Wno-long-long \
	-Wall -W -Wnested-externs \
	-Wformat=2 -Wmissing-prototypes \
	-Wstrict-prototypes \
	-Wmissing-declarations \
	-Wwrite-strings -Wshadow \
	-Wpointer-arith -Wsign-compare \
	-Wundef -Wbad-function-cast \
	-Winline -Wcast-align
am__append_4 = -DDEBUG
am__append_5 = -iquote. -I/usr/local/include
am__append_6 = -Wno-pointer-sign
#am__append_7 = -I. -I- -I/usr/local/include

# Set flags for static.
#am__append_8 = -static

# Set flags for Solaris.
#am__append_9 = -D_XPG4_2 -D__EXTENSIONS__ -D_POSIX_PTHREAD_SEMANTICS

# Set flags for Sun CC.
#am__append_10 = -erroff=E_EMPTY_DECLARATION

# Pile in all the compat/ stuff that is needed.
#am__append_11 = compat/forkpty-darwin.c
am__append_12 = compat/imsg.c compat/imsg-buffer.c
am__append_13 = compat/closefrom.c
#am__append_14 = compat/daemon.c
#am__append_15 = compat/setenv.c
#am__append_16 = compat/strlcat.c
#am__append_17 = compat/strlcpy.c
#am__append_18 = compat/asprintf.c
#am__append_19 = compat/fgetln.c
#am__append_20 = compat/getopt.c
#am__append_21 = compat/strcasestr.c
#am__append_22 = compat/strsep.c
am__append_23 = compat/vis.c compat/unvis.c
am__append_24 = compat/strtonum.c
subdir = .
DIST_COMMON = $(am__configure_deps) $(dist_man1_MANS) \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(top_srcdir)/configure TODO etc/compile etc/config.guess \
	etc/config.sub etc/depcomp etc/install-sh etc/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"
PROGRAMS = $(bin_PROGRAMS)
dist_tmux_OBJECTS = arguments.$(OBJEXT) attributes.$(OBJEXT) \
	cfg.$(OBJEXT) client.$(OBJEXT) clock.$(OBJEXT) \
	cmd-attach-session.$(OBJEXT) cmd-bind-key.$(OBJEXT) \
	cmd-break-pane.$(OBJEXT) cmd-capture-pane.$(OBJEXT) \
	cmd-choose-buffer.$(OBJEXT) cmd-choose-client.$(OBJEXT) \
	cmd-choose-session.$(OBJEXT) cmd-choose-window.$(OBJEXT) \
	cmd-clear-history.$(OBJEXT) cmd-clock-mode.$(OBJEXT) \
	cmd-command-prompt.$(OBJEXT) cmd-confirm-before.$(OBJEXT) \
	cmd-copy-mode.$(OBJEXT) cmd-delete-buffer.$(OBJEXT) \
	cmd-detach-client.$(OBJEXT) cmd-display-message.$(OBJEXT) \
	cmd-display-panes.$(OBJEXT) cmd-find-window.$(OBJEXT) \
	cmd-has-session.$(OBJEXT) cmd-if-shell.$(OBJEXT) \
	cmd-join-pane.$(OBJEXT) cmd-kill-pane.$(OBJEXT) \
	cmd-kill-server.$(OBJEXT) cmd-kill-session.$(OBJEXT) \
	cmd-kill-window.$(OBJEXT) cmd-link-window.$(OBJEXT) \
	cmd-list-buffers.$(OBJEXT) cmd-list-clients.$(OBJEXT) \
	cmd-list-commands.$(OBJEXT) cmd-list-keys.$(OBJEXT) \
	cmd-list-panes.$(OBJEXT) cmd-list-sessions.$(OBJEXT) \
	cmd-list-windows.$(OBJEXT) cmd-list.$(OBJEXT) \
	cmd-load-buffer.$(OBJEXT) cmd-lock-server.$(OBJEXT) \
	cmd-move-window.$(OBJEXT) cmd-new-session.$(OBJEXT) \
	cmd-new-window.$(OBJEXT) cmd-paste-buffer.$(OBJEXT) \
	cmd-pipe-pane.$(OBJEXT) cmd-refresh-client.$(OBJEXT) \
	cmd-rename-session.$(OBJEXT) cmd-rename-window.$(OBJEXT) \
	cmd-resize-pane.$(OBJEXT) cmd-respawn-window.$(OBJEXT) \
	cmd-rotate-window.$(OBJEXT) cmd-run-shell.$(OBJEXT) \
	cmd-save-buffer.$(OBJEXT) cmd-select-layout.$(OBJEXT) \
	cmd-select-pane.$(OBJEXT) cmd-select-window.$(OBJEXT) \
	cmd-send-keys.$(OBJEXT) cmd-send-prefix.$(OBJEXT) \
	cmd-server-info.$(OBJEXT) cmd-set-buffer.$(OBJEXT) \
	cmd-set-environment.$(OBJEXT) cmd-set-option.$(OBJEXT) \
	cmd-show-buffer.$(OBJEXT) cmd-show-environment.$(OBJEXT) \
	cmd-show-messages.$(OBJEXT) cmd-show-options.$(OBJEXT) \
	cmd-source-file.$(OBJEXT) cmd-split-window.$(OBJEXT) \
	cmd-start-server.$(OBJEXT) cmd-string.$(OBJEXT) \
	cmd-suspend-client.$(OBJEXT) cmd-swap-pane.$(OBJEXT) \
	cmd-swap-window.$(OBJEXT) cmd-switch-client.$(OBJEXT) \
	cmd-unbind-key.$(OBJEXT) cmd-unlink-window.$(OBJEXT) \
	cmd.$(OBJEXT) colour.$(OBJEXT) control.$(OBJEXT) \
	environ.$(OBJEXT) grid-utf8.$(OBJEXT) grid-view.$(OBJEXT) \
	grid.$(OBJEXT) input-keys.$(OBJEXT) input.$(OBJEXT) \
	job.$(OBJEXT) key-bindings.$(OBJEXT) key-string.$(OBJEXT) \
	layout-custom.$(OBJEXT) layout-set.$(OBJEXT) \
	layout-string.$(OBJEXT) layout.$(OBJEXT) log.$(OBJEXT) \
	mode-key.$(OBJEXT) names.$(OBJEXT) options-table.$(OBJEXT) \
	options.$(OBJEXT) paste.$(OBJEXT) resize.$(OBJEXT) \
	screen-redraw.$(OBJEXT) screen-write.$(OBJEXT) \
	screen.$(OBJEXT) server-client.$(OBJEXT) server-fn.$(OBJEXT) \
	server-window.$(OBJEXT) server.$(OBJEXT) session.$(OBJEXT) \
	signal.$(OBJEXT) status.$(OBJEXT) tmux.$(OBJEXT) \
	tty-acs.$(OBJEXT) tty-keys.$(OBJEXT) tty-term.$(OBJEXT) \
	tty.$(OBJEXT) utf8.$(OBJEXT) window-choose.$(OBJEXT) \
	window-clock.$(OBJEXT) window-copy.$(OBJEXT) window.$(OBJEXT) \
	xmalloc.$(OBJEXT) xterm-keys.$(OBJEXT)
#am__objects_1 = forkpty-darwin.$(OBJEXT)
am__objects_2 = imsg.$(OBJEXT) imsg-buffer.$(OBJEXT)
am__objects_3 = closefrom.$(OBJEXT)
#am__objects_4 = daemon.$(OBJEXT)
#am__objects_5 = setenv.$(OBJEXT)
#am__objects_6 = strlcat.$(OBJEXT)
#am__objects_7 = strlcpy.$(OBJEXT)
#am__objects_8 = asprintf.$(OBJEXT)
#am__objects_9 = fgetln.$(OBJEXT)
#am__objects_10 = getopt.$(OBJEXT)
#am__objects_11 = strcasestr.$(OBJEXT)
#am__objects_12 = strsep.$(OBJEXT)
am__objects_13 = vis.$(OBJEXT) unvis.$(OBJEXT)
am__objects_14 = strtonum.$(OBJEXT)
nodist_tmux_OBJECTS = osdep-darwin.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_9) $(am__objects_10) \
	$(am__objects_11) $(am__objects_12) $(am__objects_13) \
	$(am__objects_14)
tmux_OBJECTS = $(dist_tmux_OBJECTS) $(nodist_tmux_OBJECTS)
tmux_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/etc/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(dist_tmux_SOURCES) $(nodist_tmux_SOURCES)
DIST_SOURCES = $(dist_tmux_SOURCES)
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(dist_man1_MANS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/georgen/tmux/tmux/etc/missing --run aclocal-1.11
AMTAR = ${SHELL} /Users/georgen/tmux/tmux/etc/missing --run tar
AUTOCONF = ${SHELL} /Users/georgen/tmux/tmux/etc/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/georgen/tmux/tmux/etc/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/georgen/tmux/tmux/etc/missing --run automake-1.11
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 $(am__append_1) $(am__append_2) $(am__append_3) \
	$(am__append_6) $(am__append_10)
CPP = gcc -E

# Preprocessor flags.
CPPFLAGS =   $(am__append_4) $(am__append_5) \
	$(am__append_7) $(am__append_9)
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"1.5\" -DPACKAGE_STRING=\"tmux\ 1.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"1.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_BITSTRING_H=1 -DHAVE_CURSES_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PATHS_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_TERM_H=1 -DHAVE_UTIL_H=1 -DHAVE_FORKPTY=1 -DHAVE_DAEMON=1 -DHAVE_SETENV=1 -DHAVE_STRLCPY=1 -DHAVE_STRLCAT=1 -DHAVE_ASPRINTF=1 -DHAVE_FGETLN=1 -DHAVE_STRCASESTR=1 -DHAVE_STRSEP=1 -DHAVE_DECL_OPTARG=1 -DHAVE_DECL_OPTIND=1 -DHAVE_DECL_OPTRESET=1 -DHAVE_GETOPT=1 -DHAVE_BZERO=1 -DHAVE_SYSCONF=1 -DHAVE_BSD_TYPES=1 -DHAVE___PROGNAME=1 -DBROKEN_CMSG_FIRSTHDR=1
DEPDIR = .deps
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS =  $(am__append_8)
LIBOBJS = 
LIBS = -lcurses -levent 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/georgen/tmux/tmux/etc/missing --run makeinfo
MKDIR_P = etc/install-sh -c -d
OBJEXT = o
PACKAGE = tmux
PACKAGE_BUGREPORT = 
PACKAGE_NAME = tmux
PACKAGE_STRING = tmux 1.5
PACKAGE_TARNAME = tmux
PACKAGE_URL = 
PACKAGE_VERSION = 1.5
PATH_SEPARATOR = :
PLATFORM = darwin
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.5
XOPEN_DEFINES = 
abs_builddir = /Users/georgen/tmux/tmux
abs_srcdir = /Users/georgen/tmux/tmux
abs_top_builddir = /Users/georgen/tmux/tmux
abs_top_srcdir = /Users/georgen/tmux/tmux
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-apple-darwin10.7.0
build_alias = 
build_cpu = x86_64
build_os = darwin10.7.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-apple-darwin10.7.0
host_alias = 
host_cpu = x86_64
host_os = darwin10.7.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/georgen/tmux/tmux/etc/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/etc/install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
dist_man1_MANS = tmux.1

# Distribution tarball options.
EXTRA_DIST = \
	CHANGES FAQ NOTES TODO examples compat \
	array.h compat.h tmux.h osdep-*.c


# List of sources.
dist_tmux_SOURCES = \
	arguments.c \
	attributes.c \
	cfg.c \
	client.c \
	clock.c \
	cmd-attach-session.c \
	cmd-bind-key.c \
	cmd-break-pane.c \
	cmd-capture-pane.c \
	cmd-choose-buffer.c \
	cmd-choose-client.c \
	cmd-choose-session.c \
	cmd-choose-window.c \
	cmd-clear-history.c \
	cmd-clock-mode.c \
	cmd-command-prompt.c \
	cmd-confirm-before.c \
	cmd-copy-mode.c \
	cmd-delete-buffer.c \
	cmd-detach-client.c \
	cmd-display-message.c \
	cmd-display-panes.c \
	cmd-find-window.c \
	cmd-has-session.c \
	cmd-if-shell.c \
	cmd-join-pane.c \
	cmd-kill-pane.c \
	cmd-kill-server.c \
	cmd-kill-session.c \
	cmd-kill-window.c \
	cmd-link-window.c \
	cmd-list-buffers.c \
	cmd-list-clients.c \
	cmd-list-commands.c \
	cmd-list-keys.c \
	cmd-list-panes.c \
	cmd-list-sessions.c \
	cmd-list-windows.c \
	cmd-list.c \
	cmd-load-buffer.c \
	cmd-lock-server.c \
	cmd-move-window.c \
	cmd-new-session.c \
	cmd-new-window.c \
	cmd-paste-buffer.c \
	cmd-pipe-pane.c \
	cmd-refresh-client.c \
	cmd-rename-session.c \
	cmd-rename-window.c \
	cmd-resize-pane.c \
	cmd-respawn-window.c \
	cmd-rotate-window.c \
	cmd-run-shell.c \
	cmd-save-buffer.c \
	cmd-select-layout.c \
	cmd-select-pane.c \
	cmd-select-window.c \
	cmd-send-keys.c \
	cmd-send-prefix.c \
	cmd-server-info.c \
	cmd-set-buffer.c \
	cmd-set-environment.c \
	cmd-set-option.c \
	cmd-show-buffer.c \
	cmd-show-environment.c \
	cmd-show-messages.c \
	cmd-show-options.c \
	cmd-source-file.c \
	cmd-split-window.c \
	cmd-start-server.c \
	cmd-string.c \
	cmd-suspend-client.c \
	cmd-swap-pane.c \
	cmd-swap-window.c \
	cmd-switch-client.c \
	cmd-unbind-key.c \
	cmd-unlink-window.c \
	cmd.c \
	colour.c \
	control.c \
	environ.c \
	grid-utf8.c \
	grid-view.c \
	grid.c \
	input-keys.c \
	input.c \
	job.c \
	key-bindings.c \
	key-string.c \
	layout-custom.c \
	layout-set.c \
	layout-string.c \
	layout.c \
	log.c \
	mode-key.c \
	names.c \
	options-table.c \
	options.c \
	paste.c \
	resize.c \
	screen-redraw.c \
	screen-write.c \
	screen.c \
	server-client.c \
	server-fn.c \
	server-window.c \
	server.c \
	session.c \
	signal.c \
	status.c \
	tmux.c \
	tty-acs.c \
	tty-keys.c \
	tty-term.c \
	tty.c \
	utf8.c \
	window-choose.c \
	window-clock.c \
	window-copy.c \
	window.c \
	xmalloc.c \
	xterm-keys.c

nodist_tmux_SOURCES = osdep-darwin.c $(am__append_11) \
	$(am__append_12) $(am__append_13) $(am__append_14) \
	$(am__append_15) $(am__append_16) $(am__append_17) \
	$(am__append_18) $(am__append_19) $(am__append_20) \
	$(am__append_21) $(am__append_22) $(am__append_23) \
	$(am__append_24)
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
tmux$(EXEEXT): $(tmux_OBJECTS) $(tmux_DEPENDENCIES) 
	@rm -f tmux$(EXEEXT)
	$(LINK) $(tmux_OBJECTS) $(tmux_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/arguments.Po
include ./$(DEPDIR)/asprintf.Po
include ./$(DEPDIR)/attributes.Po
include ./$(DEPDIR)/cfg.Po
include ./$(DEPDIR)/client.Po
include ./$(DEPDIR)/clock.Po
include ./$(DEPDIR)/closefrom.Po
include ./$(DEPDIR)/cmd-attach-session.Po
include ./$(DEPDIR)/cmd-bind-key.Po
include ./$(DEPDIR)/cmd-break-pane.Po
include ./$(DEPDIR)/cmd-capture-pane.Po
include ./$(DEPDIR)/cmd-choose-buffer.Po
include ./$(DEPDIR)/cmd-choose-client.Po
include ./$(DEPDIR)/cmd-choose-session.Po
include ./$(DEPDIR)/cmd-choose-window.Po
include ./$(DEPDIR)/cmd-clear-history.Po
include ./$(DEPDIR)/cmd-clock-mode.Po
include ./$(DEPDIR)/cmd-command-prompt.Po
include ./$(DEPDIR)/cmd-confirm-before.Po
include ./$(DEPDIR)/cmd-copy-mode.Po
include ./$(DEPDIR)/cmd-delete-buffer.Po
include ./$(DEPDIR)/cmd-detach-client.Po
include ./$(DEPDIR)/cmd-display-message.Po
include ./$(DEPDIR)/cmd-display-panes.Po
include ./$(DEPDIR)/cmd-find-window.Po
include ./$(DEPDIR)/cmd-has-session.Po
include ./$(DEPDIR)/cmd-if-shell.Po
include ./$(DEPDIR)/cmd-join-pane.Po
include ./$(DEPDIR)/cmd-kill-pane.Po
include ./$(DEPDIR)/cmd-kill-server.Po
include ./$(DEPDIR)/cmd-kill-session.Po
include ./$(DEPDIR)/cmd-kill-window.Po
include ./$(DEPDIR)/cmd-link-window.Po
include ./$(DEPDIR)/cmd-list-buffers.Po
include ./$(DEPDIR)/cmd-list-clients.Po
include ./$(DEPDIR)/cmd-list-commands.Po
include ./$(DEPDIR)/cmd-list-keys.Po
include ./$(DEPDIR)/cmd-list-panes.Po
include ./$(DEPDIR)/cmd-list-sessions.Po
include ./$(DEPDIR)/cmd-list-windows.Po
include ./$(DEPDIR)/cmd-list.Po
include ./$(DEPDIR)/cmd-load-buffer.Po
include ./$(DEPDIR)/cmd-lock-server.Po
include ./$(DEPDIR)/cmd-move-window.Po
include ./$(DEPDIR)/cmd-new-session.Po
include ./$(DEPDIR)/cmd-new-window.Po
include ./$(DEPDIR)/cmd-paste-buffer.Po
include ./$(DEPDIR)/cmd-pipe-pane.Po
include ./$(DEPDIR)/cmd-refresh-client.Po
include ./$(DEPDIR)/cmd-rename-session.Po
include ./$(DEPDIR)/cmd-rename-window.Po
include ./$(DEPDIR)/cmd-resize-pane.Po
include ./$(DEPDIR)/cmd-respawn-window.Po
include ./$(DEPDIR)/cmd-rotate-window.Po
include ./$(DEPDIR)/cmd-run-shell.Po
include ./$(DEPDIR)/cmd-save-buffer.Po
include ./$(DEPDIR)/cmd-select-layout.Po
include ./$(DEPDIR)/cmd-select-pane.Po
include ./$(DEPDIR)/cmd-select-window.Po
include ./$(DEPDIR)/cmd-send-keys.Po
include ./$(DEPDIR)/cmd-send-prefix.Po
include ./$(DEPDIR)/cmd-server-info.Po
include ./$(DEPDIR)/cmd-set-buffer.Po
include ./$(DEPDIR)/cmd-set-environment.Po
include ./$(DEPDIR)/cmd-set-option.Po
include ./$(DEPDIR)/cmd-show-buffer.Po
include ./$(DEPDIR)/cmd-show-environment.Po
include ./$(DEPDIR)/cmd-show-messages.Po
include ./$(DEPDIR)/cmd-show-options.Po
include ./$(DEPDIR)/cmd-source-file.Po
include ./$(DEPDIR)/cmd-split-window.Po
include ./$(DEPDIR)/cmd-start-server.Po
include ./$(DEPDIR)/cmd-string.Po
include ./$(DEPDIR)/cmd-suspend-client.Po
include ./$(DEPDIR)/cmd-swap-pane.Po
include ./$(DEPDIR)/cmd-swap-window.Po
include ./$(DEPDIR)/cmd-switch-client.Po
include ./$(DEPDIR)/cmd-unbind-key.Po
include ./$(DEPDIR)/cmd-unlink-window.Po
include ./$(DEPDIR)/cmd.Po
include ./$(DEPDIR)/colour.Po
include ./$(DEPDIR)/control.Po
include ./$(DEPDIR)/daemon.Po
include ./$(DEPDIR)/environ.Po
include ./$(DEPDIR)/fgetln.Po
include ./$(DEPDIR)/forkpty-darwin.Po
include ./$(DEPDIR)/getopt.Po
include ./$(DEPDIR)/grid-utf8.Po
include ./$(DEPDIR)/grid-view.Po
include ./$(DEPDIR)/grid.Po
include ./$(DEPDIR)/imsg-buffer.Po
include ./$(DEPDIR)/imsg.Po
include ./$(DEPDIR)/input-keys.Po
include ./$(DEPDIR)/input.Po
include ./$(DEPDIR)/job.Po
include ./$(DEPDIR)/key-bindings.Po
include ./$(DEPDIR)/key-string.Po
include ./$(DEPDIR)/layout-custom.Po
include ./$(DEPDIR)/layout-set.Po
include ./$(DEPDIR)/layout-string.Po
include ./$(DEPDIR)/layout.Po
include ./$(DEPDIR)/log.Po
include ./$(DEPDIR)/mode-key.Po
include ./$(DEPDIR)/names.Po
include ./$(DEPDIR)/options-table.Po
include ./$(DEPDIR)/options.Po
include ./$(DEPDIR)/osdep-darwin.Po
include ./$(DEPDIR)/paste.Po
include ./$(DEPDIR)/resize.Po
include ./$(DEPDIR)/screen-redraw.Po
include ./$(DEPDIR)/screen-write.Po
include ./$(DEPDIR)/screen.Po
include ./$(DEPDIR)/server-client.Po
include ./$(DEPDIR)/server-fn.Po
include ./$(DEPDIR)/server-window.Po
include ./$(DEPDIR)/server.Po
include ./$(DEPDIR)/session.Po
include ./$(DEPDIR)/setenv.Po
include ./$(DEPDIR)/signal.Po
include ./$(DEPDIR)/status.Po
include ./$(DEPDIR)/strcasestr.Po
include ./$(DEPDIR)/strlcat.Po
include ./$(DEPDIR)/strlcpy.Po
include ./$(DEPDIR)/strsep.Po
include ./$(DEPDIR)/strtonum.Po
include ./$(DEPDIR)/tmux.Po
include ./$(DEPDIR)/tty-acs.Po
include ./$(DEPDIR)/tty-keys.Po
include ./$(DEPDIR)/tty-term.Po
include ./$(DEPDIR)/tty.Po
include ./$(DEPDIR)/unvis.Po
include ./$(DEPDIR)/utf8.Po
include ./$(DEPDIR)/vis.Po
include ./$(DEPDIR)/window-choose.Po
include ./$(DEPDIR)/window-clock.Po
include ./$(DEPDIR)/window-copy.Po
include ./$(DEPDIR)/window.Po
include ./$(DEPDIR)/xmalloc.Po
include ./$(DEPDIR)/xterm-keys.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

forkpty-darwin.o: compat/forkpty-darwin.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT forkpty-darwin.o -MD -MP -MF $(DEPDIR)/forkpty-darwin.Tpo -c -o forkpty-darwin.o `test -f 'compat/forkpty-darwin.c' || echo '$(srcdir)/'`compat/forkpty-darwin.c
	$(am__mv) $(DEPDIR)/forkpty-darwin.Tpo $(DEPDIR)/forkpty-darwin.Po
#	source='compat/forkpty-darwin.c' object='forkpty-darwin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o forkpty-darwin.o `test -f 'compat/forkpty-darwin.c' || echo '$(srcdir)/'`compat/forkpty-darwin.c

forkpty-darwin.obj: compat/forkpty-darwin.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT forkpty-darwin.obj -MD -MP -MF $(DEPDIR)/forkpty-darwin.Tpo -c -o forkpty-darwin.obj `if test -f 'compat/forkpty-darwin.c'; then $(CYGPATH_W) 'compat/forkpty-darwin.c'; else $(CYGPATH_W) '$(srcdir)/compat/forkpty-darwin.c'; fi`
	$(am__mv) $(DEPDIR)/forkpty-darwin.Tpo $(DEPDIR)/forkpty-darwin.Po
#	source='compat/forkpty-darwin.c' object='forkpty-darwin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o forkpty-darwin.obj `if test -f 'compat/forkpty-darwin.c'; then $(CYGPATH_W) 'compat/forkpty-darwin.c'; else $(CYGPATH_W) '$(srcdir)/compat/forkpty-darwin.c'; fi`

imsg.o: compat/imsg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT imsg.o -MD -MP -MF $(DEPDIR)/imsg.Tpo -c -o imsg.o `test -f 'compat/imsg.c' || echo '$(srcdir)/'`compat/imsg.c
	$(am__mv) $(DEPDIR)/imsg.Tpo $(DEPDIR)/imsg.Po
#	source='compat/imsg.c' object='imsg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o imsg.o `test -f 'compat/imsg.c' || echo '$(srcdir)/'`compat/imsg.c

imsg.obj: compat/imsg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT imsg.obj -MD -MP -MF $(DEPDIR)/imsg.Tpo -c -o imsg.obj `if test -f 'compat/imsg.c'; then $(CYGPATH_W) 'compat/imsg.c'; else $(CYGPATH_W) '$(srcdir)/compat/imsg.c'; fi`
	$(am__mv) $(DEPDIR)/imsg.Tpo $(DEPDIR)/imsg.Po
#	source='compat/imsg.c' object='imsg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o imsg.obj `if test -f 'compat/imsg.c'; then $(CYGPATH_W) 'compat/imsg.c'; else $(CYGPATH_W) '$(srcdir)/compat/imsg.c'; fi`

imsg-buffer.o: compat/imsg-buffer.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT imsg-buffer.o -MD -MP -MF $(DEPDIR)/imsg-buffer.Tpo -c -o imsg-buffer.o `test -f 'compat/imsg-buffer.c' || echo '$(srcdir)/'`compat/imsg-buffer.c
	$(am__mv) $(DEPDIR)/imsg-buffer.Tpo $(DEPDIR)/imsg-buffer.Po
#	source='compat/imsg-buffer.c' object='imsg-buffer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o imsg-buffer.o `test -f 'compat/imsg-buffer.c' || echo '$(srcdir)/'`compat/imsg-buffer.c

imsg-buffer.obj: compat/imsg-buffer.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT imsg-buffer.obj -MD -MP -MF $(DEPDIR)/imsg-buffer.Tpo -c -o imsg-buffer.obj `if test -f 'compat/imsg-buffer.c'; then $(CYGPATH_W) 'compat/imsg-buffer.c'; else $(CYGPATH_W) '$(srcdir)/compat/imsg-buffer.c'; fi`
	$(am__mv) $(DEPDIR)/imsg-buffer.Tpo $(DEPDIR)/imsg-buffer.Po
#	source='compat/imsg-buffer.c' object='imsg-buffer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o imsg-buffer.obj `if test -f 'compat/imsg-buffer.c'; then $(CYGPATH_W) 'compat/imsg-buffer.c'; else $(CYGPATH_W) '$(srcdir)/compat/imsg-buffer.c'; fi`

closefrom.o: compat/closefrom.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT closefrom.o -MD -MP -MF $(DEPDIR)/closefrom.Tpo -c -o closefrom.o `test -f 'compat/closefrom.c' || echo '$(srcdir)/'`compat/closefrom.c
	$(am__mv) $(DEPDIR)/closefrom.Tpo $(DEPDIR)/closefrom.Po
#	source='compat/closefrom.c' object='closefrom.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o closefrom.o `test -f 'compat/closefrom.c' || echo '$(srcdir)/'`compat/closefrom.c

closefrom.obj: compat/closefrom.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT closefrom.obj -MD -MP -MF $(DEPDIR)/closefrom.Tpo -c -o closefrom.obj `if test -f 'compat/closefrom.c'; then $(CYGPATH_W) 'compat/closefrom.c'; else $(CYGPATH_W) '$(srcdir)/compat/closefrom.c'; fi`
	$(am__mv) $(DEPDIR)/closefrom.Tpo $(DEPDIR)/closefrom.Po
#	source='compat/closefrom.c' object='closefrom.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o closefrom.obj `if test -f 'compat/closefrom.c'; then $(CYGPATH_W) 'compat/closefrom.c'; else $(CYGPATH_W) '$(srcdir)/compat/closefrom.c'; fi`

daemon.o: compat/daemon.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT daemon.o -MD -MP -MF $(DEPDIR)/daemon.Tpo -c -o daemon.o `test -f 'compat/daemon.c' || echo '$(srcdir)/'`compat/daemon.c
	$(am__mv) $(DEPDIR)/daemon.Tpo $(DEPDIR)/daemon.Po
#	source='compat/daemon.c' object='daemon.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o daemon.o `test -f 'compat/daemon.c' || echo '$(srcdir)/'`compat/daemon.c

daemon.obj: compat/daemon.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT daemon.obj -MD -MP -MF $(DEPDIR)/daemon.Tpo -c -o daemon.obj `if test -f 'compat/daemon.c'; then $(CYGPATH_W) 'compat/daemon.c'; else $(CYGPATH_W) '$(srcdir)/compat/daemon.c'; fi`
	$(am__mv) $(DEPDIR)/daemon.Tpo $(DEPDIR)/daemon.Po
#	source='compat/daemon.c' object='daemon.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o daemon.obj `if test -f 'compat/daemon.c'; then $(CYGPATH_W) 'compat/daemon.c'; else $(CYGPATH_W) '$(srcdir)/compat/daemon.c'; fi`

setenv.o: compat/setenv.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT setenv.o -MD -MP -MF $(DEPDIR)/setenv.Tpo -c -o setenv.o `test -f 'compat/setenv.c' || echo '$(srcdir)/'`compat/setenv.c
	$(am__mv) $(DEPDIR)/setenv.Tpo $(DEPDIR)/setenv.Po
#	source='compat/setenv.c' object='setenv.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o setenv.o `test -f 'compat/setenv.c' || echo '$(srcdir)/'`compat/setenv.c

setenv.obj: compat/setenv.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT setenv.obj -MD -MP -MF $(DEPDIR)/setenv.Tpo -c -o setenv.obj `if test -f 'compat/setenv.c'; then $(CYGPATH_W) 'compat/setenv.c'; else $(CYGPATH_W) '$(srcdir)/compat/setenv.c'; fi`
	$(am__mv) $(DEPDIR)/setenv.Tpo $(DEPDIR)/setenv.Po
#	source='compat/setenv.c' object='setenv.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o setenv.obj `if test -f 'compat/setenv.c'; then $(CYGPATH_W) 'compat/setenv.c'; else $(CYGPATH_W) '$(srcdir)/compat/setenv.c'; fi`

strlcat.o: compat/strlcat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strlcat.o -MD -MP -MF $(DEPDIR)/strlcat.Tpo -c -o strlcat.o `test -f 'compat/strlcat.c' || echo '$(srcdir)/'`compat/strlcat.c
	$(am__mv) $(DEPDIR)/strlcat.Tpo $(DEPDIR)/strlcat.Po
#	source='compat/strlcat.c' object='strlcat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strlcat.o `test -f 'compat/strlcat.c' || echo '$(srcdir)/'`compat/strlcat.c

strlcat.obj: compat/strlcat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strlcat.obj -MD -MP -MF $(DEPDIR)/strlcat.Tpo -c -o strlcat.obj `if test -f 'compat/strlcat.c'; then $(CYGPATH_W) 'compat/strlcat.c'; else $(CYGPATH_W) '$(srcdir)/compat/strlcat.c'; fi`
	$(am__mv) $(DEPDIR)/strlcat.Tpo $(DEPDIR)/strlcat.Po
#	source='compat/strlcat.c' object='strlcat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strlcat.obj `if test -f 'compat/strlcat.c'; then $(CYGPATH_W) 'compat/strlcat.c'; else $(CYGPATH_W) '$(srcdir)/compat/strlcat.c'; fi`

strlcpy.o: compat/strlcpy.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strlcpy.o -MD -MP -MF $(DEPDIR)/strlcpy.Tpo -c -o strlcpy.o `test -f 'compat/strlcpy.c' || echo '$(srcdir)/'`compat/strlcpy.c
	$(am__mv) $(DEPDIR)/strlcpy.Tpo $(DEPDIR)/strlcpy.Po
#	source='compat/strlcpy.c' object='strlcpy.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strlcpy.o `test -f 'compat/strlcpy.c' || echo '$(srcdir)/'`compat/strlcpy.c

strlcpy.obj: compat/strlcpy.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strlcpy.obj -MD -MP -MF $(DEPDIR)/strlcpy.Tpo -c -o strlcpy.obj `if test -f 'compat/strlcpy.c'; then $(CYGPATH_W) 'compat/strlcpy.c'; else $(CYGPATH_W) '$(srcdir)/compat/strlcpy.c'; fi`
	$(am__mv) $(DEPDIR)/strlcpy.Tpo $(DEPDIR)/strlcpy.Po
#	source='compat/strlcpy.c' object='strlcpy.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strlcpy.obj `if test -f 'compat/strlcpy.c'; then $(CYGPATH_W) 'compat/strlcpy.c'; else $(CYGPATH_W) '$(srcdir)/compat/strlcpy.c'; fi`

asprintf.o: compat/asprintf.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT asprintf.o -MD -MP -MF $(DEPDIR)/asprintf.Tpo -c -o asprintf.o `test -f 'compat/asprintf.c' || echo '$(srcdir)/'`compat/asprintf.c
	$(am__mv) $(DEPDIR)/asprintf.Tpo $(DEPDIR)/asprintf.Po
#	source='compat/asprintf.c' object='asprintf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o asprintf.o `test -f 'compat/asprintf.c' || echo '$(srcdir)/'`compat/asprintf.c

asprintf.obj: compat/asprintf.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT asprintf.obj -MD -MP -MF $(DEPDIR)/asprintf.Tpo -c -o asprintf.obj `if test -f 'compat/asprintf.c'; then $(CYGPATH_W) 'compat/asprintf.c'; else $(CYGPATH_W) '$(srcdir)/compat/asprintf.c'; fi`
	$(am__mv) $(DEPDIR)/asprintf.Tpo $(DEPDIR)/asprintf.Po
#	source='compat/asprintf.c' object='asprintf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o asprintf.obj `if test -f 'compat/asprintf.c'; then $(CYGPATH_W) 'compat/asprintf.c'; else $(CYGPATH_W) '$(srcdir)/compat/asprintf.c'; fi`

fgetln.o: compat/fgetln.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT fgetln.o -MD -MP -MF $(DEPDIR)/fgetln.Tpo -c -o fgetln.o `test -f 'compat/fgetln.c' || echo '$(srcdir)/'`compat/fgetln.c
	$(am__mv) $(DEPDIR)/fgetln.Tpo $(DEPDIR)/fgetln.Po
#	source='compat/fgetln.c' object='fgetln.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o fgetln.o `test -f 'compat/fgetln.c' || echo '$(srcdir)/'`compat/fgetln.c

fgetln.obj: compat/fgetln.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT fgetln.obj -MD -MP -MF $(DEPDIR)/fgetln.Tpo -c -o fgetln.obj `if test -f 'compat/fgetln.c'; then $(CYGPATH_W) 'compat/fgetln.c'; else $(CYGPATH_W) '$(srcdir)/compat/fgetln.c'; fi`
	$(am__mv) $(DEPDIR)/fgetln.Tpo $(DEPDIR)/fgetln.Po
#	source='compat/fgetln.c' object='fgetln.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o fgetln.obj `if test -f 'compat/fgetln.c'; then $(CYGPATH_W) 'compat/fgetln.c'; else $(CYGPATH_W) '$(srcdir)/compat/fgetln.c'; fi`

getopt.o: compat/getopt.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT getopt.o -MD -MP -MF $(DEPDIR)/getopt.Tpo -c -o getopt.o `test -f 'compat/getopt.c' || echo '$(srcdir)/'`compat/getopt.c
	$(am__mv) $(DEPDIR)/getopt.Tpo $(DEPDIR)/getopt.Po
#	source='compat/getopt.c' object='getopt.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o getopt.o `test -f 'compat/getopt.c' || echo '$(srcdir)/'`compat/getopt.c

getopt.obj: compat/getopt.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT getopt.obj -MD -MP -MF $(DEPDIR)/getopt.Tpo -c -o getopt.obj `if test -f 'compat/getopt.c'; then $(CYGPATH_W) 'compat/getopt.c'; else $(CYGPATH_W) '$(srcdir)/compat/getopt.c'; fi`
	$(am__mv) $(DEPDIR)/getopt.Tpo $(DEPDIR)/getopt.Po
#	source='compat/getopt.c' object='getopt.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o getopt.obj `if test -f 'compat/getopt.c'; then $(CYGPATH_W) 'compat/getopt.c'; else $(CYGPATH_W) '$(srcdir)/compat/getopt.c'; fi`

strcasestr.o: compat/strcasestr.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strcasestr.o -MD -MP -MF $(DEPDIR)/strcasestr.Tpo -c -o strcasestr.o `test -f 'compat/strcasestr.c' || echo '$(srcdir)/'`compat/strcasestr.c
	$(am__mv) $(DEPDIR)/strcasestr.Tpo $(DEPDIR)/strcasestr.Po
#	source='compat/strcasestr.c' object='strcasestr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strcasestr.o `test -f 'compat/strcasestr.c' || echo '$(srcdir)/'`compat/strcasestr.c

strcasestr.obj: compat/strcasestr.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strcasestr.obj -MD -MP -MF $(DEPDIR)/strcasestr.Tpo -c -o strcasestr.obj `if test -f 'compat/strcasestr.c'; then $(CYGPATH_W) 'compat/strcasestr.c'; else $(CYGPATH_W) '$(srcdir)/compat/strcasestr.c'; fi`
	$(am__mv) $(DEPDIR)/strcasestr.Tpo $(DEPDIR)/strcasestr.Po
#	source='compat/strcasestr.c' object='strcasestr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strcasestr.obj `if test -f 'compat/strcasestr.c'; then $(CYGPATH_W) 'compat/strcasestr.c'; else $(CYGPATH_W) '$(srcdir)/compat/strcasestr.c'; fi`

strsep.o: compat/strsep.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strsep.o -MD -MP -MF $(DEPDIR)/strsep.Tpo -c -o strsep.o `test -f 'compat/strsep.c' || echo '$(srcdir)/'`compat/strsep.c
	$(am__mv) $(DEPDIR)/strsep.Tpo $(DEPDIR)/strsep.Po
#	source='compat/strsep.c' object='strsep.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strsep.o `test -f 'compat/strsep.c' || echo '$(srcdir)/'`compat/strsep.c

strsep.obj: compat/strsep.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strsep.obj -MD -MP -MF $(DEPDIR)/strsep.Tpo -c -o strsep.obj `if test -f 'compat/strsep.c'; then $(CYGPATH_W) 'compat/strsep.c'; else $(CYGPATH_W) '$(srcdir)/compat/strsep.c'; fi`
	$(am__mv) $(DEPDIR)/strsep.Tpo $(DEPDIR)/strsep.Po
#	source='compat/strsep.c' object='strsep.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strsep.obj `if test -f 'compat/strsep.c'; then $(CYGPATH_W) 'compat/strsep.c'; else $(CYGPATH_W) '$(srcdir)/compat/strsep.c'; fi`

vis.o: compat/vis.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT vis.o -MD -MP -MF $(DEPDIR)/vis.Tpo -c -o vis.o `test -f 'compat/vis.c' || echo '$(srcdir)/'`compat/vis.c
	$(am__mv) $(DEPDIR)/vis.Tpo $(DEPDIR)/vis.Po
#	source='compat/vis.c' object='vis.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o vis.o `test -f 'compat/vis.c' || echo '$(srcdir)/'`compat/vis.c

vis.obj: compat/vis.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT vis.obj -MD -MP -MF $(DEPDIR)/vis.Tpo -c -o vis.obj `if test -f 'compat/vis.c'; then $(CYGPATH_W) 'compat/vis.c'; else $(CYGPATH_W) '$(srcdir)/compat/vis.c'; fi`
	$(am__mv) $(DEPDIR)/vis.Tpo $(DEPDIR)/vis.Po
#	source='compat/vis.c' object='vis.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o vis.obj `if test -f 'compat/vis.c'; then $(CYGPATH_W) 'compat/vis.c'; else $(CYGPATH_W) '$(srcdir)/compat/vis.c'; fi`

unvis.o: compat/unvis.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT unvis.o -MD -MP -MF $(DEPDIR)/unvis.Tpo -c -o unvis.o `test -f 'compat/unvis.c' || echo '$(srcdir)/'`compat/unvis.c
	$(am__mv) $(DEPDIR)/unvis.Tpo $(DEPDIR)/unvis.Po
#	source='compat/unvis.c' object='unvis.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o unvis.o `test -f 'compat/unvis.c' || echo '$(srcdir)/'`compat/unvis.c

unvis.obj: compat/unvis.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT unvis.obj -MD -MP -MF $(DEPDIR)/unvis.Tpo -c -o unvis.obj `if test -f 'compat/unvis.c'; then $(CYGPATH_W) 'compat/unvis.c'; else $(CYGPATH_W) '$(srcdir)/compat/unvis.c'; fi`
	$(am__mv) $(DEPDIR)/unvis.Tpo $(DEPDIR)/unvis.Po
#	source='compat/unvis.c' object='unvis.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o unvis.obj `if test -f 'compat/unvis.c'; then $(CYGPATH_W) 'compat/unvis.c'; else $(CYGPATH_W) '$(srcdir)/compat/unvis.c'; fi`

strtonum.o: compat/strtonum.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strtonum.o -MD -MP -MF $(DEPDIR)/strtonum.Tpo -c -o strtonum.o `test -f 'compat/strtonum.c' || echo '$(srcdir)/'`compat/strtonum.c
	$(am__mv) $(DEPDIR)/strtonum.Tpo $(DEPDIR)/strtonum.Po
#	source='compat/strtonum.c' object='strtonum.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strtonum.o `test -f 'compat/strtonum.c' || echo '$(srcdir)/'`compat/strtonum.c

strtonum.obj: compat/strtonum.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strtonum.obj -MD -MP -MF $(DEPDIR)/strtonum.Tpo -c -o strtonum.obj `if test -f 'compat/strtonum.c'; then $(CYGPATH_W) 'compat/strtonum.c'; else $(CYGPATH_W) '$(srcdir)/compat/strtonum.c'; fi`
	$(am__mv) $(DEPDIR)/strtonum.Tpo $(DEPDIR)/strtonum.Po
#	source='compat/strtonum.c' object='strtonum.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strtonum.obj `if test -f 'compat/strtonum.c'; then $(CYGPATH_W) 'compat/strtonum.c'; else $(CYGPATH_W) '$(srcdir)/compat/strtonum.c'; fi`
install-man1: $(dist_man1_MANS)
	@$(NORMAL_INSTALL)
	test -z "$(man1dir)" || $(MKDIR_P) "$(DESTDIR)$(man1dir)"
	@list='$(dist_man1_MANS)'; test -n "$(man1dir)" || exit 0; \
	{ for i in $$list; do echo "$$i"; done; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_man1_MANS)'; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	test -z "$$files" || { \
	  echo " ( cd '$(DESTDIR)$(man1dir)' && rm -f" $$files ")"; \
	  cd "$(DESTDIR)$(man1dir)" && rm -f $$files; }

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@list='$(MANS)'; if test -n "$$list"; then \
	  list=`for p in $$list; do \
	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
	  if test -n "$$list" && \
	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
	    exit 1; \
	  else :; fi; \
	else :; fi
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(MANS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-man

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man: install-man1

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-man

uninstall-man: uninstall-man1

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-hook dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-man1 install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-man \
	uninstall-man1

dist-hook:
	grep "^#found_debug=" configure
	find $(distdir) -name CVS -type d|xargs rm -Rf

# Update SF web site.
upload-index.html: update-index.html
	scp www/index.html www/main.css www/images/*.png \
		${USER},tmux@web.sf.net:/home/groups/t/tm/tmux/htdocs
	rm -f www/index.html www/images/small-*

update-index.html:
	(cd www/images && \
		rm -f small-* && \
		for i in *.png; do \
			convert "$$i" -resize 200x150 "small-$$i"; \
		done \
	)
	sed "s/%%VERSION%%/${VERSION}/g" www/index.html.in >www/index.html

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
